### ISSUE TITLE
Recupero informazioni CIE

### ISSUE THREAD

**Issue by adelmassimo** [italia/cie-middleware-windows-docs#1]
Salve,
per un particolare sviluppo necessito di popolare un form di dati anagrafici (es. nome + cognome + residenza) attraverso la lettura di CIE. Questo caso d'uso è supportato dal middleware? Sto cercando nella direzione sbagliata?
Grazie mille

**Comment by aantetomaso** [comment]
Salve, 

non è con il Software CIE che si può implementare questa funzionalità. Per la lettura dei dati le consiglio di visionare la MRTD SDK su Developers Italia e l'applicazione Desktop di esempio.

https://github.com/italia/cie-mrtd-example-app
https://github.com/italia/cie-mrtd-dotnet-sdk
